### PR TITLE
Adjust the PID gains for the vel_based_pos_traj_controller to reasona…

### PR DESCRIPTION
**Pull request by AndyZe**
…ble values, for the UR3.

### CODE REVIEW

**Comment by miguelprada** [comment]
I was about to start working on a PR enabling the [velocity feedforward term](https://wiki.ros.org/joint_trajectory_controller?distro=kinetic#Parameters) (way too many details [here](https://github.com/ros-controls/ros_controllers/pull/227)) in the different `vel_based_pos_traj_controller` default configurations, which in theory should allow to reduce the PID gains even further.

Would you mind trying to enable this and adjusting the gains again? If your method to determine the gains is reproducible, I could then contribute to this PR by repeating it on a UR5 and a UR10.

**Comment by miguelprada** [comment]
Oops, I just realized you opened this PR against my `iss/206` branch, which is probably not the best idea. You should probably rebase on top of `kinetic-devel` in the upstream repo and target that branch.

**Comment by miguelprada** [comment]
One more thing, @AndyZe.

Did you try those gains with the action interface of the controller? I'm surprised so small gains don't produce tolerance violations, and therefore cause the actions to fail.

**Comment by AndyZe** [comment]
You're right, the gains did need to be larger for the action server.

I like your idea of using a feedforward velocity term. I'll play with it briefly but it's really beyond the scope of my present work.

**Comment by AndyZe** [comment]
Feedforward was actually easy to implement and it works great!

**Pull request closed without merging**
